### ISSUE TITLE
Remove Vehicle storage

### ISSUE THREAD

**Issue by sercanatici** [EpochSC/SingleCurrencyStorage#29]
Is there a way to remove the storage for vehicles only? So only vault and lockbox have money storage.

**Comment by Windmolders** [comment]
remove the following lines

https://github.com/EpochSC/SingleCurrencyStorage/blob/master/DayZ_Epoch_11.Chernarus/ZSC/compiles/fn_selfActions.sqf#L504-L512

**Comment by sercanatici** [comment]
Thanks this will help me alot against dupers
