### ISSUE TITLE
anti dupe

### ISSUE THREAD

**Issue by sercanatici** [EpochSC/SingleCurrencyStorage#30]
i have patched up the give to another player dupe. When two players opens up the give money to "player", and both gives the same amount it dupes the money. I am looking for something similar to when some one goes into the money storage in a vault. Both of them takes the same amount and they dupe it. So is there a way to prevent them in this like only allowing one guy at the time on money storage?

Cheers

**Comment by Windmolders** [comment]
You can build it a distance check for players in the vicinity on the following file. You can pass that to and if check, if it fails display a message?

https://github.com/EpochSC/SingleCurrencyStorage/blob/master/DayZ_Epoch_11.Chernarus/ZSC/actions/bank_dialog.sqf#L3

**Comment by sercanatici** [comment]
Build a distance check for player, could be nice, how would i do this?

**Comment by sercanatici** [comment]
will still do it ?

if(DZE_ActionInProgress) exitWith { cutText [(localize "str_epoch_player_10") , "PLAIN DOWN"]; };
DZE_ActionInProgress = true;

private ["_dialog"];
ZSC_CurrentStorage = _this select 3;
_dialog = createDialog "BankDialog";
call BankDialogUpdateAmounts;
player setVariable ["tradingmoney", true, true];
[] spawn {
	while {dialog} do {
		if (GivePlayerTarget getVariable ["tradingmoney", false]) exitWith {
			closeDialog 0;
		};
		uiSleep 0.25;
	};
};
waitUntil {uiSleep 1; !dialog};
player setVariable ["tradingmoney", false, true];
DZE_ActionInProgress = false;

**Comment by sercanatici** [comment]
I just tested this and it didnt work like my give_player_dialog.sqf.
private ["_dialog"];
GivePlayerTarget = _this select 3;

if (GivePlayerTarget getVariable ["tradingmoney", false]) exitWith {
	cutText ["You can not give to someone who is already trading.", "PLAIN DOWN"];
};

_dialog = createdialog "GivePlayerDialog";
call GivePlayerDialogAmounts;
player setVariable ["tradingmoney", true, true];
[] spawn {
	while {dialog} do {
		if (GivePlayerTarget getVariable ["tradingmoney", false]) exitWith {
			closeDialog 0;
		};
		uiSleep 0.25;
	};
};
waitUntil {uiSleep 1; !dialog};
player setVariable ["tradingmoney", false, true];

**Comment by Windmolders** [comment]
wait, this is giving money, not putting it in the storage

**Comment by sercanatici** [comment]
Hmm, can you help me solve the dupe ?

**Comment by Windmolders** [comment]
https://github.com/EpochSC/SingleCurrencyStorage/blob/master/DayZ_Epoch_11.Chernarus/ZSC/actions/bank_dialog.sqf

**Comment by sercanatici** [comment]
This worked thanks alot youre the best.
